
# source 'https://github.com/ruiying123/Spec.git'

source 'https://github.com/CocoaPods/Specs.git'

target 'BingoDemo' do

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

# pod 'podTest', '~> 1.0.0'
pod 'YRExtension', '~> 0.0.6’

end

